# Generated by Django 2.2.3 on 2020-07-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearReportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
